version: "3"

services:
  restfulexample:
    image: jiezhang/restfulexample
    ports:
      - "8888:8080"
    networks:
      - back-tier

  webexample:
    image: jiezhang/webexample
    ports:
      - "8000:8080"
    environment:
      - devops_exmple_url=http://restfulexample:8080/RESTfulExample/rest/person/
    depends_on:
      - restfulexample
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:
